### ISSUE TITLE
Adicionar seção sobre conteúdo alternativo para multimídia

### ISSUE THREAD

**Issue by mateuscgc** [InfoJrUFBA/Guia-de-Estilo-InfoJr-UFBA#12]
#### Conteúdo alternativo para multimídia
Para multimídia, como por exemplo imagens e vídeos, procure fornecer conteúdo alternativo para acessibilidade.

Imagem com proposito puramente decorativo, que por algum motivo não pode ser atribuída por CSS, não deve ter acesso alternativo.

```html
<!-- Recomendado -->
<img src="info.png" alt="Logo InfoJr">
```

**Comment by ramos13** [comment]
Seção adicionada!
