### ISSUE TITLE
Alteração na seção "Idioma"

### ISSUE THREAD

**Issue by mateuscgc** [InfoJrUFBA/Guia-de-Estilo-InfoJr-UFBA#3]
#### 1.2 Idioma
Todo o código deve ser escrito em Inglês, com exceção do conteúdo que vai ser apresentado ao usuário final~~, este último deve ser escrito em português do Brasil~~ **que deve ser escrito na(s) linguagem(ns) especificadas para o produto**.

**Comment by ramos13** [comment]
Sugestão aceita!
