### ISSUE TITLE
Seção "Última linha" com mesmo conteúdo da seção "Idioma"

### ISSUE THREAD

**Issue by mateuscgc** [InfoJrUFBA/Guia-de-Estilo-InfoJr-UFBA#4]
#### 1.3 Última linha
Todo o código deve ser escrito em Inglês, com exceção do conteúdo que vai ser apresentado ao usuário final, este último deve ser escrito em português do Brasil.

**Comment by ramos13** [comment]
Acabei escrevendo o mesmo texto em dois parágrafos e por conta disso o parágrafo foi retirado.
