### ISSUE TITLE
Exemplo item 1.6

### ISSUE THREAD

**Issue by aobruno** [InfoJrUFBA/Guia-de-Estilo-InfoJr-UFBA#6]
Faltou um exemplo prático de como utilizar um comentário

**Comment by ramos13** [comment]
O tópico 1.6 passou a ser 1.5, e os comentários solicitados foram incluídos.

**Comment by mateuscgc** [comment]
Eu tava junto com Davi quando o texto dessa seção foi feito, pelo que eu me lembro a ideia seria que o comentário fosse explicado no guia da própria linguagem, por isso não teria exemplo nessa seção.
No caso teria que mudar um ou o outro

Aproveitando sugiro essa mudança no texto da seção

#### 1.5 Comentários
**Conforme necessário,** utilize ~~os~~ comentários para explicar ~~o código, conforme necessário,~~ **um trecho de código,** ~~sempre que preciso.~~ indicando o que ele cobre, qual a finalidade, ~~para que serve~~ etc. ~~Isso~~ **O uso de comentários** facilita a compreensão do ~~mesmo por outras pessoas que tiverem acesso ao seu código~~**código por outros desenvolvedores**. Para fazer um comentário~~, para cada linguagem com a qual estiver desenvolvendo, use~~ **utilize** de preferência a marcação indicada no guia de estilo ~~referente a essa linguagem~~**da linguagem em questão**.

To reabrindo a issue para que @ramos13 dê uma olhada
