### ISSUE TITLE
Numeração dos subitens do terceiro nível em "Regras de Estilo"

### ISSUE THREAD

**Issue by aobruno** [InfoJrUFBA/Guia-de-Estilo-InfoJr-UFBA#7]
EX:

2.1.1 Tipo de Documento
...

2.1.2 Escrita
...

E assim por diante

**Comment by ramos13** [comment]
@aobruno eu tinha evitado a numeração dos subintes para que a pagina referente a cada tópico não ficasse tão massante. E a nível de organização acredito  que o mesmo não fara tanta falta, pq em todos os outros tópicos, seguem um padrão, então fora esses requesitos, qual seria a intenção de numerar os subitens?

**Comment by ramos13** [comment]
@vncdias @jprodrigues70 @mateuscgc oq vocês acham? quero a opnião de vocês nisso aqui, se possível

**Comment by mateuscgc** [comment]
Para mim tanto faz, mas em ultimo caso acho que deixaria sem.

Sugiro na verdade que tire o título repetido de cada uma dessas páginas, ex:

### ~~Guia de Estilo~~

# ~~2.1 HTML~~

Essa numeração 2.1... seria legal no nome da página, com isso a nav ao lado direito ficaria organizada
