### ISSUE TITLE
Exemplificar os itens da seção de JavaScript

### ISSUE THREAD

**Issue by aobruno** [InfoJrUFBA/Guia-de-Estilo-InfoJr-UFBA#8]
Essa seção está carente de exemplos nos dois primeiros itens

**Comment by RafaelBarretto** [comment]
Exemplos para adição:
 <script> alert("Hello! Eu tô no guia de estilo!!"); </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.jquery.min.js"></script>
</body>
</html>

**Comment by ramos13** [comment]
Exemplo inserido!
